### ISSUE TITLE
Color Palette for the theme for porting purposes.

### ISSUE THREAD

**Issue by adityamwagh** [volkovpishet/one-calm-theme-vscode#1]
Great theme, very easy on the eyes! Will it be possible to provide the color palette to port it to other tools & editors?

**Comment by volkovpishet** [comment]
Hi, @adityamwagh Thanks for your suggestion )

For anyone who is interested in **porting this theme to other editors** see below paths to investigate color palette:

- The main color palette is described in `generator/theme/colors.ts`
- Semantic token colors for `code highlighting` are described in `generator/theme/semantic-colors.ts`
- Standard token colors for  `code highlighting` are in `generator/theme/theme.ts`
- IDE specific colors (panels, status bars, etc.) are described in `generator/theme/editor.ts`
